name: OWASP ZAP Scan

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
       docker_name: 'owasp/zap2docker-stable'
       target: 'https://nginxappy.newcross-sbx.com/'
       rules_file_name: '.zap/rules.tsv'
       cmd_options: '-a'
      env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       AWS_REGION: us-east-1
  # Upload report to S3
    - name: Upload Report to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
        from: ./zap/wrk
        to: s3://iac-instance-newcross/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1


